# Generated by Django 6.0.3 on 2026-04-05 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('68c3664e-9f65-4b2b-b47f-1d99900db944'), primary_key=True, serialize=False),
        ),
    ]
