# Generated by Django 6.0.3 on 2026-04-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_deleted_at_post_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
